#!/usr/bin/python

# CPClient
#
# Copyright (C) 2011 Intel Corporation. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU Lesser General Public License,
# version 2.1, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
#
# Mark Ryan <mark.d.ryan@intel.com>

import dbus
import sys
import os
import array

bus = dbus.SessionBus()

if len(sys.argv) < 2:
	sys.exit("Usage: parsewp filename pin\n")

fname = sys.argv[1]
if len(sys.argv) == 3:
	pin = sys.argv[2]
else:
	pin = ""

fd = open(fname, "rb")
try:
	message_size = os.path.getsize(sys.argv[1])
	message = array.array('B',[])
	message.fromfile(fd,message_size)
finally:
	fd.close()

manager = dbus.Interface(bus.get_object('com.intel.cpclient.server', '/com/intel/cpclient'),
					'com.intel.cpclient.Manager')
path = manager.CreatePushMessage(message)
try:
	pm = dbus.Interface(bus.get_object('com.intel.cpclient.server', path),
					'com.intel.cpclient.PushMessage')
	print pm.GetProps()
	pm.Apply(pin)
	print "Message Applied"
except dbus.exceptions.DBusException, err:
	print "Unable to process WAP Push message: ", err
finally:
	pm.Close()

